Migrated to SALOBJ6. Also updated the Docker image used for testing t…
lsst-ts/ts_GenericCamera pull request #10
Opened 2020-10-13 12:49 UTC by wvreeven

…o use SALOBJ6 and install python-gphoto2 from sources pulled from GitHub.

2020-10-27 18:02 UTC, tribeiro requested changes
This looks pretty good. Had only a small change in code that I suggest you consider but there are all these License strings thatI think need revision. For some reasons they have DM where it should be TSS.

2020-10-28 10:16 UTC, wvreeven commented on python/lsst/ts/GenericCamera/driver/canoncamera.py
> +        imageformat.set_value("Large Fine JPEG")
Interesting comment that seems to favor a specific coding style. Other reviewers usually prefer to not do this in a single line. I have changed it in this case, however, in this and the next 4 lines.

2020-10-28 10:18 UTC, wvreeven commented on python/lsst/ts/GenericCamera/driver/canoncamera.py
>          # This starts the exposure while obtaining the path to the file on the
Good suggestion. Done for both this and the endReadout methods.

2020-10-28 10:18 UTC, wvreeven commented on python/lsst/ts/GenericCamera/exposure.py
> +# Developed for the LSST Data Management System.
Yes, this should be "LSST Telescope and Site Systems". I corrected this in all Python files in this project.

2020-10-28 10:20 UTC, wvreeven commented
Changes pushed. Please have another look at the code.

2020-10-28 22:16 UTC, tribeiro approved these changes
Good! thanks for the changes.

2020-10-29 09:19 UTC, merged