snake_case bool_to_int and start_readout
lsst-ts/ts_genericcamera pull request #23
Opened 2022-04-14 14:14 UTC by pkubanek

2022-04-14 14:34 UTC, wvreeven requested changes
This is a good start. But many methonds with camelCase names remain, like `_assertHandle`, `stopExposure` and many more. The tricky part of this ticket is to replace all camelCase variable and method names with snake_case but leave the ones that refer to native variables and methods in place.

2022-04-14 22:16 UTC, wvreeven requested changes
Another great improvement. However, I found a few more candidates and will admit that I didn't scrutinize the code files. Please have another look and change all that are possible. Sorry to be a pain.

2022-04-14 22:16 UTC, wvreeven commented on python/lsst/ts/genericcamera/driver/zwocamera.py
>          cameraProperty = ASICameraInfoCtypes()
I think that `cameraProperty` is a candidate as well.

2022-04-14 22:16 UTC, wvreeven commented on python/lsst/ts/genericcamera/driver/zwocamera.py
>      def getCameraPropertyByID(self, id):
I think that `getCameraPropertyByID` is a candidate as well.

2022-04-14 22:16 UTC, wvreeven commented on python/lsst/ts/genericcamera/driver/zwocamera.py
>      def openCamera(self, id):
I think that `openCamera` is a candidate as well.

2022-04-14 22:16 UTC, wvreeven commented on python/lsst/ts/genericcamera/driver/zwocamera.py
>      def initCamera(self, id):
I think that `initCamera` is a candidate as well.

2022-04-14 22:16 UTC, wvreeven commented on python/lsst/ts/genericcamera/driver/zwocamera.py
>      def closeCamera(self, id):
I think that `closeCamera` is a candidate as well.

2022-04-14 22:16 UTC, wvreeven commented on python/lsst/ts/genericcamera/driver/andorcamera.py
>      def setAccumulateCount(self, value):
I think that `setAccumulateCount` is a candidate as well.

2022-04-14 22:16 UTC, wvreeven commented on python/lsst/ts/genericcamera/driver/andorcamera.py
>      def cmdAcquisitionStart(self):
I think that `cmdAcquisitionStart` is a candidate as well.

2022-07-01 07:02 UTC, pkubanek commented
I removed hopefully last snakeCase artefacts, please have a look. Tests shall be passing.

2022-07-01 10:45 UTC, wvreeven commented
Unfortunately one test case fails and flake8 isn't happy either. Please review the failures and fix the code accordingly.

2022-07-04 10:21 UTC, wvreeven approved these changes
Loooks MUCH better than before. The members of the `ASICameraInfo` class (in zwocamera.py) should be renamed as well. There still are several `_assertConnected` methonds in the liveview module. There are `startLiveView` and `stopLiveView` functions in the `EUI` class (in liveviewui.py). Otherwise fine.

2022-07-04 11:32 UTC, merged